{{- if .Values.allocationAwareness.enabled }}
kind: ClusterRole
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "common.names.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "opensearch.data.serviceAccountName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
  - kind: ServiceAccount
    name: {{ template "opensearch.cluster_manager.serviceAccountName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
  - kind: ServiceAccount
    name: {{ template "opensearch.ingest.serviceAccountName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
  - kind: ServiceAccount
    name: {{ template "opensearch.coordinating.serviceAccountName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
{{- end }}