{{- if or .Values.ingest.serviceAccount.create .Values.allocationAwareness.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opensearch.ingest.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ingest
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .Values.ingest.serviceAccount.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.ingest.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ingest.serviceAccount.annotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- if .Values.allocationAwareness.enabled }}
automountServiceAccountToken: true
{{- else }}
automountServiceAccountToken: {{ .Values.ingest.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}